version: '3.3'
services:
  saranghaengbok:
    build: .
    image: tubes-1:latest
    ports:
      - 8008:80
    environment:
      DB_HOST: db
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
volumes:
  db_data:
