version: '3.3'
services:
  saranghaengbok:
    build: .
    image: tubes-1:latest
    ports:
      - 8008:80
    environment:
      DB_HOST: db
  db:
    image: mysql:latest
    ports:
      - 6603:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_HOST=db
volumes:
  db_data:
