version: '3.3'
services:
  php-app:
    build:
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - 8008:80
    environment:
      DB_URL: mysql://db-php-app/saranghaengbok_php
  
